### ISSUE TITLE
Include non-standard status codes

### ISSUE THREAD

**Issue by iliazeus** [jschauma/httpstatus#2]
Most of the time, when I'm looking up a status code, it is not a standard one, since I already know most of them, but a nonstandard one - often Cloudflare-specific, for example. Because of that, it will be very useful to also have non-standard codes documented here - specifying that they are, in fact, non-standard, of course.

**Comment by iliazeus** [comment]
Wikipedia [has a list](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Unofficial_codes) of such codes, and its license should allow it to be copy-pasted here, with attribution.

**Comment by hdhoang** [comment]
we recently had to deal with status 000 in nginx log, because of http2 goaway. it's quite un-searchable. I would like to add some docs for it too if you agree

**Comment by jschauma** [comment]
I just added a bunch of non-standard HTTP status codes from various places.  If you know of others, happy to receive pull requests or just open a new issue!
